#! /bin/sh

xsetroot -cursor_name left_ptr &
sxhkd &
picom &
killall redshift && redshift -l manual &
# killall nm-applet && nm-applet &
# killall volumeicon && volumeicon &
$HOME/.config/polybar/launch.sh &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

if test "$(bspc query -M | wc -l)" -gt 1; then
    bspc monitor primary -d 1 2 3 4 5
    bspc monitor ^2 -d 6 7 8 9 0
fi

# Hide polybar under fullscreen windows
bspc subscribe node_add | while read -r event; do
    # Get ID of the focused desktop
    desktop=$(bspc query -D -d focused --names)

    # Check if the focused desktop has a fullscreen window
    if bspc query -N -d "$desktop" -n "fullscreen"; then
        # Get ID of the polybar on the focused desktop
        polybar_id=$(xdo id -a "polybar-bspwm-$desktop")

        # Hide the polybar
        xdo hide -a "$polybar_id"
    fi
done &

# Show polybar when fullscreen window is destroyed
bspc subscribe node_remove | while read -r event; do
    # Get ID of the focused desktop
    desktop=$(bspc query -D -d focused --names)

    # Check if the focused desktop has any windows
    if bspc query -N -d "$desktop" -n .; then
        # Get ID of the polybar on the focused desktop
        polybar_id=$(xdo id -a "polybar-bspwm-$desktop")

        # Show the polybar
        xdo show -a "$polybar_id"
    fi
done &

bspc config window_gap                  1
bspc config border_radius               1
bspc config border_width                1
bspc config top_padding                 0
bspc config right_padding               0
bspc config bottom_padding              0
bspc config left_padding                0

bspc config split_ratio                 0.50
bspc config single_monocle              false
bspc config borderless_monocle          true
bspc config gapless_monocle             true

bspc config pointer_modifier            mod4
bspc config pointer_action1             move
bspc config pointer_action2             resize_side
bspc config pointer_action3             resize_corner
bspc config pointer_follows_focus       false
bspc config pointer_follows_monitor     false

bspc config click_to_focus              false#button1
bspc config swallow_first_click         false
bspc config focus_follows_pointer       true
bspc config focus_by_distance           true
bspc config history_aware_focus         true

bspc config remove_unplugged_monitors   true
bspc config remove_disabled_monitors    true
bspc config merge_overlapping_monitors  true

bspc config normal_border_color         "#4c566a"
bspc config active_border_color	        "#5e81ac"
bspc config focused_border_color	    "#FFFFFF"
bspc config presel_feedback_color	    "#5e69ac"
bspc config urgent_border_color 	    "#dd2727"

bspc rule -a Pavucontrol state=floating
bspc rule -a Gimp state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
