#! /bin/sh

xsetroot -cursor_name left_ptr &
setxkbmap gb &
[ $(ps -aux | grep 'picom$' | wc -l) -eq 0 ] && picom &
[ $(ps -aux | grep 'volumeicon$' | wc -l) -ge 1 ] && killall volumeicon
volumeicon &
nm-applet &
$HOME/.config/polybar/launch.sh &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

if test "$(bspc query -M | wc -l)" -eq 2; then
    bspc monitor primary -d 1 2 3 4 5
    bspc monitor ^2 -d 6 7 8 9 0
fi

bspc config window_gap                  1
bspc config border_radius               1
bspc config border_width                1
bspc config top_padding                 0
bspc config right_padding               0
bspc config bottom_padding              0
bspc config left_padding                0

bspc config split_ratio                 0.50
bspc config single_monocle              false
bspc config borderless_monocle          true
bspc config gapless_monocle             true

bspc config pointer_modifier            mod4
bspc config pointer_action1             move
bspc config pointer_action2             resize_side
bspc config pointer_action3             resize_corner
bspc config pointer_follows_focus       false
bspc config pointer_follows_monitor     false

bspc config click_to_focus              false #button1
bspc config swallow_first_click         false
bspc config focus_follows_pointer       true

bspc config remove_unplugged_monitors   true
bspc config remove_disabled_monitors    true
bspc config merge_overlapping_monitors  true

bspc config normal_border_color         "#333333"
bspc config active_border_color	        "#5e81ac"
bspc config focused_border_color	    "#999999"
bspc config presel_feedback_color	    "#5e69ac"

bspc rule -a Pavucontrol state=floating
bspc rule -a Gimp state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
